# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Adamâ€™s Tech Blog
tagline:          'Hacks and Magic'
description:      'Filled with little coding notes and fixes. Also check out my <a href="http://adamj.eu">main blog</a> for an online magazine experience.'
url:              http://adamj.eu/tech/
baseurl:          /tech

author:
  name:           'Adam Johnson'
  url:            https://github.com/adamchainz
  email:          me@adamj.eu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/adamchainz/techblog
