# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: [tables]
highlighter:      pygments

gems:
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Adam’s Tech Blog
tagline:          'Hacks and Magic'
description:      'Filled with little coding notes and fixes. Also check out my <a href="http://adamj.eu">main blog</a> for an ‘online magazine experience.’'
url:              http://adamj.eu/tech/
baseurl:          /tech

exclude:          ['*.ipynb', '*.py']

author:
  name:           'Adam Johnson'
  url:            https://github.com/adamchainz
  email:          me@adamj.eu

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/adamchainz/techblog


# jekyll-tagging plugin
tag_page_layout: tag_page
tag_page_dir: tag
